---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: FIXME_APPNAME
  namespace: FIXME_APPNAME
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: FIXME_APPNAME
  strategy:
    blueGreen:
      activeService: FIXME_APPNAME
      previewService: FIXME_APPNAME-preview
      autoPromotionEnabled: false
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: FIXME_APPNAME

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: FIXME_APP_NAME-preview
  name: FIXME_APP_NAME-preview
  namespace: FIXME_APP_NAME
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: FIXME_PORT
  selector:
    app: FIXME_APP_NAME
  type: LoadBalancer
